# Generated by Django 4.1 on 2022-08-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invista_me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='nivel',
            field=models.FloatField(default=0),
        ),
    ]
